version: "3"
services:
    php:
        build:
            dockerfile: php.Dockerfile
            context: .
        volumes:
            - .:/opt/project
            - ../docs:/data/docs
            - ../specifications:/data/specifications
            - ../computable:/data/computable
            - ../codegen:/data/codegen
        tty: true
        user: 1000:1000
